# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/sample-deployment-settings.yml
---
restrictedRepos:
  # these repos are all archived and will cause the GHA to fail
  # https://github.com/github/safe-settings/issues/443
  exclude:
    - ^OIDC-Authentication$
    - ^eks-github-runner$
